### ISSUE TITLE
Revert commit 7447eb0a14bfcba44be5b0d53905f931078bb395

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#62]
Once upstream bug https://github.com/graugans/meta-udoo/issues/3 is fixed, update submodule `meta-udoo` and revert commit 7447eb0a14bfcba44be5b0d53905f931078bb395.

Run a scratch build "bitbake core-image-minimal" and verify that there is no regression.

See related issue https://github.com/gmacario/easy-jenkins/issues/57

**Comment by graugans** [comment]
Any suggestion how to fix this in a right way?

**Comment by gmacario** [comment]
Hi @graugans,

Unfortunately haven't investigated it in depth, but AFAIK there should be a missing `DEPENDS` in `core-image-minimal.bb` or one of its depending packages

**Comment by graugans** [comment]
I will add m4-firmware to [MACHINE_ESSENTIAL_EXTRA_RDEPENDS](http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#var-MACHINE_ESSENTIAL_EXTRA_RDEPENDS) It is a bit to much because the m4 firmware is not essential for the boot process but in case of [MACHINE_EXTRA_RDEPENDS](http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#var-MACHINE_EXTRA_RDEPENDS) ``core-image-minimal`` will not contain m4-firmware because it does not contain ``packagegroup-base``

**Comment by RoydAmias** [comment]
This can be officially closed now that https://github.com/graugans/meta-udoo/issues/3 is closed right?
